
package com.teckwave.Status;
/*
 * AGB.java
 *
 * Created on 8. Juli 2007, 18:09
 */

/**
 *
 * @author  bcypher
 */
 import javax.swing.*;
 import java.awt.*;
 import com.teckwave.Status.*;
 import com.teckwave.Protokoll.*;
 import javax.swing.text.html.HTMLEditorKit;
 import java.awt.*;
import java.awt.event.*;
import java.util.*;
import java.net.*;
import javax.swing.*;
import javax.swing.text.*;
import javax.swing.text.html.*;
public class AGB extends javax.swing.JDialog {
    
    /** Creates new form AGB */
    String mData=null;
    public AGB(JDialog parent, boolean modal, String data) {
        super(parent, modal);
        initComponents();
        mData=data;
        
//        jEditorPane1.setContentType("text/html");
  //      FillField();
    }
    
    private void InsertData()
    {
        Util.DownloadURL("http://www.teckwave.de/hotspot/registrieren.php",mData, "POST");
    }
    
    public void FillField()
    {
        String[] text=Util.DownloadURL("http://www.teckwave.de/hotspot/agb.html","","GET");
        String ntext=new String("");
        for(int i=0;i<text.length;i++)
        {
            ntext+=text[i];
        }
        jEditorPane1.setText(ntext);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Erzeugter Quelltext ">                          
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = null;
        try{jEditorPane1 = new javax.swing.JEditorPane("http://www.teckwave.de/hotspot/agb.html");}catch(Exception e){}
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jScrollPane1.setViewportView(jEditorPane1);

        jButton1.setText("Akzeptieren");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ablehnen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jButton1)
                        .addGap(37, 37, 37)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
            this.hide();// TODO Ihre Ereignisbehandlung hier einfügen:
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
            InsertData();
            this.hide();
    }                                        
    
    /**
     * @param args the command line arguments
     */
    
    // Variablendeklaration - nicht modifizieren                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // Ende der Variablendeklaration                   
    
}
